version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atsashas_art_app
    restart: unless-stopped
    expose:
      - "80" # ДОЛЖЕН быть массив

  caddy:
    image: caddy:2.8-alpine
    container_name: atsashas_art_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    volumes:
      - ./deploy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
